# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: event-pump release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      NAMESPACE_UUID: c1811956-6f34-11ee-b962-0242ac120002
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm i --legacy-peer-deps
      - run: npm test
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAMESPACE_UUID: ${{ secrets.NAMESPACE_UUID }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      NAMESPACE_UUID: ${{ secrets.NAMESPACE_UUID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: npm publish
       
